WEBCAM_INDEX = 1
SENSITIVITY = 120
PATH = "C:\\Captures"
MAX_RESOLUTION = True # HD: 1280x720

DISPLAY_BRAND = True
DISPLAY_FRAMES = True
DISPLAY_NOTIFICATION = True
DISPLAY_FRAMES_DIFFERENCE = True

INITIAL_DELAY = 10 # Second(s)
CAPTURE_INTERVAL = 1 # Second(s)
