WEBCAM_INDEX = 0
SENSITIVITY = 120
PATH = "C:\\Captures"
MAX_RESOLUTION = True  # HD: 1280x720

DISPLAY_FRAMES = True
PUT_TEXT_ON_FRAME = True
DISPLAY_NOTIFICATION = True
DISPLAY_FRAMES_DIFFERENCE = True

INITIAL_DELAY = 10  # Second(s)
CAPTURE_INTERVAL = 1  # Second(s)

BRAND = "Dariush Tasdighi - @IranianExperts - 09121087461"
